[project]
name = "flask-debug"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "flask-debugtoolbar>=0.16.0",
    "flask-sqlalchemy>=3.1.1",
]
